const SHOP_DATA = [
	{
		title: 'Vape',
		items: [
			{
				id: 1,
				name: 'Smok Nord 4',
				// imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
				imageUrl: 'https://i.ibb.co/GQN5TLW/smok-nord-4.jpg',
				price: 1500,
			},
			{
				id: 2,
				name: 'Voopoo Argus Pro',
				// imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
				imageUrl: 'https://i.ibb.co/2McGL9W/voopoo-argus-pro.jpg',
				price: 1000,
			},
			{
				id: 3,
				name: 'Oxva X-Slim Pro',
				// imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
				imageUrl: 'https://i.ibb.co/g4cdMY7/oxva-xslim-pro.jpg',
				price: 890,
			},
			{
				id: 4,
				name: 'Oxva Vativ',
				// imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
				imageUrl: 'https://i.ibb.co/1zYyX9x/oxva-vativ.jpg',
				price: 2999,
			},
			{
				id: 5,
				name: 'Aegis Solo 2',
				// imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
				imageUrl: 'https://i.ibb.co/7JBXrf7/aegis-solo-2.jpg',
				price: 2100,
			},
			{
				id: 6,
				name: 'SMOK RPM 5 Vape',
				// imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
				imageUrl: 'https://i.ibb.co/JdVmRJd/SMOK-RPM-5-Vape.jpg',
				price: 1899,
			},
			{
				id: 7,
				name: 'Oxva Xking Vape Pod',
				// imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
				imageUrl: 'https://i.ibb.co/QMd0BP2/Oxva-Xking-Vape-Pod.jpg',
				price: 671,
			},
			{
				id: 8,
				name: 'Puff Bar Vape Pod',
				// imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
				imageUrl: 'https://i.ibb.co/SVyXbvn/Puff-Bar-Vape-Pod.jpg',
				price: 92,
			},
			{
				id: 9,
				name: 'Geekvape Wenax Stylus Vape Pod',
				// imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
				imageUrl: 'https://i.ibb.co/D5D07sk/Geekvape-Wenax-Stylus-Vape-Pod.jpg',
				price: 1195,
			},
		],
	},
	{
		title: 'Cap',
		items: [
			{
				id: 10,
				name: 'Sinio Cap 3',
				// imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
				imageUrl: 'https://i.ibb.co/YkzZPq7/cap-sinio-3.jpg',
				price: 380,
			},
			{
				id: 11,
				name: 'Sinio Cap 1',
				// imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
				imageUrl: 'https://i.ibb.co/3739cz4/cap-sinio-1.jpg',
				price: 300,
			},
			{
				id: 12,
				name: 'Sinio Cap 2',
				// imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
				imageUrl: 'https://i.ibb.co/jW2krYX/cap-sinio-2.jpg',
				price: 330,
			},
			{
				id: 13,
				name: 'Raiders 1',
				// imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
				imageUrl: 'https://i.ibb.co/k0rD1mX/raiders-1.jpg',
				price: 250,
			},
			{
				id: 14,
				name: 'Raiders 2',
				// imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
				imageUrl: 'https://i.ibb.co/P676Mh1/raiders-2.jpg',
				price: 600,
			},
			{
				id: 15,
				name: 'Highminds Cap 1',
				// imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
				imageUrl: 'https://i.ibb.co/9nYTqwk/highminds-1.jpg',
				price: 450,
			},
			{
				id: 16,
				name: 'Highminds Cap 2',
				// imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
				imageUrl: 'https://i.ibb.co/SJ1Ftzw/highminds-2.jpg',
				price: 399,
			},
			{
				id: 17,
				name: 'Highminds Cap 3',
				// imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
				imageUrl: 'https://i.ibb.co/xq5jxRY/highminds-3.jpg',
				price: 400,
			},
		],
	},
	{
		title: 'T-Shirt',
		items: [
			{
				id: 18,
				name: 'Oversize Pink',
				// imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
				imageUrl: 'https://i.ibb.co/16DNHxk/oversize.jpg',
				price: 899,
			},
			{
				id: 19,
				name: 'Stig BnK Flow-G',
				// imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
				imageUrl: 'https://i.ibb.co/T41dM8y/stig.jpg',
				price: 999,
			},
			{
				id: 20,
				name: 'Peace White',
				// imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
				imageUrl: 'https://i.ibb.co/X788szp/peace.jpg',
				price: 399,
			},
			{
				id: 21,
				name: 'Highminds Clothing',
				// imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
				imageUrl: 'https://i.ibb.co/DMdncXh/highminds-3.jpg',
				price: 499,
			},
			{
				id: 22,
				name: 'Highminds Clothing 2',
				// imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
				imageUrl: 'https://i.ibb.co/jyMtQSh/highminds-2.jpg',
				price: 599,
			},
			{
				id: 100,
				name: 'Highminds Clothing 3',
				// imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
				imageUrl: 'https://i.ibb.co/pP0vWv9/highminds-1.jpg',
				price: 699,
			},
		],
	},
	{
		title: 'Sneakers',
		items: [
			{
				id: 23,
				name: 'Basketball Shoes 1',
				// imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
				imageUrl: 'https://i.ibb.co/h7XYyN2/shoes-4.jpg',
				price: 2999,
			},
			{
				id: 24,
				name: 'Basketball Shoes 2',
				// imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
				imageUrl: 'https://i.ibb.co/r3KM2vc/shoes-5.jpg',
				price: 10990,
			},
			{
				id: 25,
				name: 'Nike Shoes (1)',
				// imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
				imageUrl: 'https://i.ibb.co/sKzNGCz/shoes-3.jpg',
				price: 9799,
			},
			{
				id: 26,
				name: 'Converse',
				// imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
				imageUrl: 'https://i.ibb.co/WFhPrqC/shoes-2.jpg',
				price: 5799,
			},
			{
				id: 27,
				name: 'Sneaker (1)',
				// imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
				imageUrl: 'https://i.ibb.co/8X9yn7v/shoes-1.jpg',
				price: 4599,
			},
			{
				id: 28,
				name: 'Sneaker (2)',
				// imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
				imageUrl: 'https://i.ibb.co/ncDnQX2/sneaker-1.jpg',
				price: 7999,
			},
			{
				id: 29,
				name: 'Sneaker (3)',
				// imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
				imageUrl: 'https://i.ibb.co/QMscZDX/sneaker-2.jpg',
				price: 5999,
			},
		],
	},
	{
		title: 'Smartphones',
		items: [
			{
				id: 30,
				name: 'Iphone 14 Pro Max 1T',
				// imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
				imageUrl: 'https://i.ibb.co/J7v4YGR/iphone14.jpg',
				price: 109990,
			},
			{
				id: 31,
				name: 'Realme GT',
				// imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
				imageUrl: 'https://i.ibb.co/8X5ygfw/realmeGT.png',
				price: 30815,
			},
			{
				id: 32,
				name: 'Samsung Galaxy Z Flip',
				// imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
				imageUrl: 'https://i.ibb.co/rsL7fDF/samsung-flip.jpg',
				price: 39799,
			},
			{
				id: 33,
				name: 'Realme 10 Pro',
				// imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
				imageUrl: 'https://i.ibb.co/3cNkVTP/realme10pro.jpg',
				price: 18999,
			},
			{
				id: 34,
				name: 'Huawei P50',
				// imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
				imageUrl: 'https://i.ibb.co/DY1Sxjd/huawei-P50.jpg',
				price: 39999,
			},
			{
				id: 35,
				name: 'Vivo V27 5G',
				// imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
				imageUrl: 'https://i.ibb.co/St8wWq4/vivo-v27-5g.jpg',
				price: 24999,
			},
		],
	},
];

export default SHOP_DATA;
